name: Rust Tests

permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "android-app"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --locked --lib
